import { VarGroup } from '@stylexjs/stylex';

export type TSizes = Readonly<{
  spacing_0: string;
  spacing_25: string;
  spacing_50: string;
  spacing_100: string;
  spacing_200: string;
  spacing_300: string;
  spacing_400: string;
  spacing_500: string;
  spacing_600: string;
  spacing_650: string;
  spacing_700: string;
  spacing_800: string;
  spacing_900: string;
  spacing_1000: string;
  spacing_1200: string;
  spacing_1300: string;
  border_sm: string;
  border_md: string;
  radius_xs: string;
  radius_sm: string;
  radius_md: string;
  radius_lg: string;
  radius_full: string;
  column_narrow: string;
  column_regular: string;
  column_wide: string;
  column_xs: string;
  column_sm: string;
  column_md: string;
  column_lg: string;
  column_xl: string;
  column_xxl: string;
  min_width_narrow: string;
  min_width_regular: string;
  min_width_wide: string;
  min_width_xs: string;
  min_width_sm: string;
  min_width_md: string;
  min_width_lg: string;
  min_width_xl: string;
  min_width_xxl: string;
  gutter: string;
  margin: string;
  fixed_container_narrow: string;
  fixed_container_regular: string;
  fixed_container_wide: string;
  fixed_container_xs: string;
  fixed_container_sm: string;
  fixed_container_md: string;
  fixed_container_lg: string;
  fixed_container_xl: string;
  fixed_container_xxl: string;
}>;

export declare const sizes: VarGroup<TSizes>;
